[package]
name = "udpunch"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9"

[[bin]]
name = "listener"
path = "src/bins/listener.rs"

[[example]]
name = "client"
path = "examples/client.rs"
